### ISSUE TITLE
On the vaults page the lettering loads poorly

### ISSUE THREAD

**Issue by obnoxiousmods** [spectrumprotocol/frontend#36]
There is a number counting / loading effect on https://terra.spec.finance/vaults and in newest Brave it loads very poorly constantly needing a refresh or it will slow to a hault and show wrong number or freezing when tabbed out etc

**Comment by SpectrumRhealward** [comment]
This has been resolved in new UI upgrade.

**Comment by obnoxiousmods** [comment]
Hello this still happens, cant give 10000% accurate steps to reproduce but it definitely still happens, with super fast testing i tried to make it happen manually but it wouldnt go but when i was afk for a bit and came back to my PC and it was doing it in Brave
